INSERT INTO Brand (Br_title)
VALUES 
('Himalaya Baby'),
('MAGGI'),
('Milky Mist'),
('Gillette'),
('Kelloggs'),
('Sofit'),
('TRESemme'),
('Piknik'),
('Epigamia'),
('Surf Excel'),
('BB Home Earth'),
('Eveready'),
('Clean & Clear'),
('Srushti Gold'),
('Dabur'),
('Mr. Gold'),
('Meera'),
('Harpic'),
('Engage'),
('Nescafe'),
('24 Mantra'),
('BB Royal Organic'),
('Red Label'),
('Close Up'),
('iD Fresho'),
('Cadbury Dairy Milk'),
('Nandini'),
('Saffola'),
('Ponds'),
('BB Home'),
('bb Combo'),
('Pepsi'),
('Amul'),
('Asian'),
('Fresho'),
('Gowardhan'),
('Pedigree'),
('Unibic'),
('Happilo'),
('Whisper'),
('Loreal Paris'),
('Clinic Plus'),
('Sunfeast'),
('Taj Mahal'),
('Tata Coffee'),
('Del Monte'),
('Dettol'),
('Yummiez'),
('Hersheys'),
('BORGES'),
('Colgate'),
('Wingreens Farms'),
('Domex'),
('Laplast'),
('Kitchen Essentials'),
('Super Saver'),
('Lotus Herbals'),
('Aashirvaad'),
('AKSHAYAKALPA'),
('BB Popular'),
('Nirlon'),
('Tata Tea Gold'),
('Princeware'),
('Parachute'),
('Pantene'),
('Quaker'),
('AKAR'),
('HappyChef'),
('Closeup'),
('Set Wet'),
('Nivea Men'),
('Mamypoko'),
('Godrej Protekt'),
('Maybelline New York'),
('PEPPY'),
('Energizer'),
('Head & shoulders'),
('Polyset'),
('Dove'),
('GREEN KIVVI'),
('Axe'),
('Pampers'),
('MTR'),
('Fresho Signature'),
('Huggies'),
('Ariel'),
('Raw Pressery'),
('Real'),
('Fortune'),
('Fresho Organic'),
('Emperia'),
('Tata Sampann'),
('Cello'),
('Himalaya'),
('Tasties'),
('Bingo'),
('GoodDiet'),
('Go'),
('BB Royal'),
('Cavins'),
('Olay'),
('Rexona'),
('Sunsilk'),
('Lindberg'),
('Palmolive'),
('Top Ramen'),
('Sugarlite'),
('Lakme'),
('Daawat'),
('Fiona'),
('Cadbury'),
('Mountain Dew'),
('Nivea'),
('Parachute Advansed'),
('STAYFREE'),
('Fiama'),
('Vaseline'),
('Octus'),
('Elephant'),
('Godrej Nupur'),
('Tang');
